import {
  type RefUser,
  type IWorkspace,
  type IProject,
  type IBoard,
  type ISprint,
  type ITask,
} from "@/types/task";

export const ME: RefUser = { id: "u_me", name: "You (Developer)", email: "you@nimbus.io" };

export const USERS: RefUser[] = [
  ME,
  { id: "u_aditi", name: "Aditi Sharma", email: "aditi@nimbus.io" },
  { id: "u_rohan", name: "Rohan Mehta", email: "rohan@nimbus.io" },
  { id: "u_priya", name: "Priya Nair", email: "priya@nimbus.io" },
  { id: "u_karan", name: "Karan Verma", email: "karan@nimbus.io" },
  { id: "u_sara", name: "Sara Iqbal", email: "sara@nimbus.io" },
];

export const WORKSPACES: IWorkspace[] = [
  {
    id: "ws_acme",
    name: "Acme Enterprise",
    description: "Main organization workspace for flagship products.",
    color: "#0F2D29",
    icon: "💼",
    owner: USERS[1],
    members: USERS.map((u) => ({ user: u, role: u.id === "u_aditi" ? "owner" : "member", joinedAt: "2026-01-15" })),
    isPrivate: false,
    createdAt: "2026-01-10T10:00:00Z",
    updatedAt: "2026-08-01T10:00:00Z",
  },
  {
    id: "ws_devstudio",
    name: "DevStudio Global",
    description: "Engineering and R&D workspace for experimental apps.",
    color: "#0F2D29",
    icon: "⚡",
    owner: USERS[2],
    members: USERS.map((u) => ({ user: u, role: "member", joinedAt: "2026-02-01" })),
    isPrivate: false,
    createdAt: "2026-02-01T10:00:00Z",
    updatedAt: "2026-08-05T10:00:00Z",
  },
  {
    id: "ws_fintech",
    name: "Fintech Labs",
    description: "Secure payment gateway and compliance workspace.",
    color: "#0F2D29",
    icon: "🛡️",
    owner: USERS[3],
    members: USERS.map((u) => ({ user: u, role: "member", joinedAt: "2026-03-10" })),
    isPrivate: true,
    createdAt: "2026-03-01T10:00:00Z",
    updatedAt: "2026-08-08T10:00:00Z",
  },
];

export const PROJECTS: IProject[] = [
  {
    id: "proj_web",
    name: "Website Redesign Q3",
    description: "Complete modern redesign of customer portal and marketing site.",
    workspace: WORKSPACES[0],
    owner: USERS[1],
    members: USERS.map((u) => ({ user: u, role: { id: "r_dev", name: "Developer" }, joinedAt: "2026-05-01" })),
    tasks: [],
    color: "#0F2D29",
    status: "active",
    progress: 68,
    isArchived: false,
    startDate: "2026-06-01T00:00:00Z",
    dueDate: "2026-09-30T00:00:00Z",
    createdAt: "2026-05-01T10:00:00Z",
    updatedAt: "2026-08-09T10:00:00Z",
  },
  {
    id: "proj_mobile",
    name: "Mobile App V2",
    description: "Cross-platform React Native iOS and Android app update.",
    workspace: WORKSPACES[0],
    owner: USERS[2],
    members: USERS.map((u) => ({ user: u, role: { id: "r_dev", name: "Developer" }, joinedAt: "2026-05-15" })),
    tasks: [],
    color: "#0F2D29",
    status: "active",
    progress: 45,
    isArchived: false,
    startDate: "2026-06-15T00:00:00Z",
    dueDate: "2026-10-15T00:00:00Z",
    createdAt: "2026-05-15T10:00:00Z",
    updatedAt: "2026-08-08T10:00:00Z",
  },
  {
    id: "proj_cloud",
    name: "Cloud Infra Migration",
    description: "Migrating core services to AWS EKS microservices architecture.",
    workspace: WORKSPACES[1],
    owner: USERS[2],
    members: USERS.map((u) => ({ user: u, role: { id: "r_devops", name: "DevOps" }, joinedAt: "2026-06-01" })),
    tasks: [],
    color: "#0F2D29",
    status: "planning",
    progress: 20,
    isArchived: false,
    startDate: "2026-07-01T00:00:00Z",
    dueDate: "2026-11-30T00:00:00Z",
    createdAt: "2026-06-01T10:00:00Z",
    updatedAt: "2026-08-07T10:00:00Z",
  },
  {
    id: "proj_pay",
    name: "Payment Gateway Integration",
    description: "Stripe & PayPal webhooks with instant invoice generation.",
    workspace: WORKSPACES[2],
    owner: USERS[3],
    members: USERS.map((u) => ({ user: u, role: { id: "r_backend", name: "Backend Lead" }, joinedAt: "2026-07-01" })),
    tasks: [],
    color: "#0F2D29",
    status: "active",
    progress: 82,
    isArchived: false,
    startDate: "2026-07-01T00:00:00Z",
    dueDate: "2026-08-31T00:00:00Z",
    createdAt: "2026-07-01T10:00:00Z",
    updatedAt: "2026-08-10T10:00:00Z",
  },
];

export const BOARDS: IBoard[] = [
  {
    id: "board_redesign",
    name: "Redesign Kanban Board",
    workspace: WORKSPACES[0],
    project: PROJECTS[0],
    description: "Main task board for Q3 marketing and portal redesign.",
    type: "kanban",
    columns: ["Backlog", "To Do", "In Progress", "In Review", "Testing", "Completed"],
    createdBy: USERS[1],
    createdAt: "2026-05-02T10:00:00Z",
    updatedAt: "2026-08-01T10:00:00Z",
  },
  {
    id: "board_mobile",
    name: "Mobile App Sprint 14",
    workspace: WORKSPACES[0],
    project: PROJECTS[1],
    description: "Scrum board for active sprint tasks.",
    type: "scrum",
    columns: ["Backlog", "To Do", "In Progress", "In Review", "Done"],
    createdBy: USERS[2],
    createdAt: "2026-05-16T10:00:00Z",
    updatedAt: "2026-08-02T10:00:00Z",
  },
  {
    id: "board_cloud",
    name: "Cloud Infra Tracker",
    workspace: WORKSPACES[1],
    project: PROJECTS[2],
    description: "Kanban board for Kubernetes & Terraform pipeline.",
    type: "kanban",
    columns: ["Backlog", "To Do", "In Progress", "Completed"],
    createdBy: USERS[2],
    createdAt: "2026-06-02T10:00:00Z",
    updatedAt: "2026-08-03T10:00:00Z",
  },
];

export const SPRINTS: ISprint[] = [
  { id: "sp_14", name: "Sprint 14 (July 28 - Aug 10)", status: "active", startDate: "2026-07-28", endDate: "2026-08-10" },
  { id: "sp_15", name: "Sprint 15 (Aug 11 - Aug 24)", status: "planned", startDate: "2026-08-11", endDate: "2026-08-24" },
];

const daysOffset = (days: number) => {
  const d = new Date();
  d.setDate(d.getDate() + days);
  return d.toISOString();
};

export const INITIAL_TASKS: ITask[] = [
  {
    id: "task_1",
    title: "Design homepage hero & interactive prototype",
    description: "Create high-fidelity Figma components, dark mode variants, and interactive micro-animations for desktop & mobile viewports.",
    board: BOARDS[0],
    project: PROJECTS[0],
    workspace: WORKSPACES[0],
    sprint: SPRINTS[0],
    column: "In Progress",
    assignee: ME,
    watchers: [USERS[1], USERS[3]],
    status: "in_progress",
    priority: "high",
    tags: ["design", "hero", "figma"],
    dueDate: daysOffset(3),
    estimatedHours: 12,
    actualHours: 8.5,
    subtasks: [
      { id: "st_1", title: "Explore 3 typography & layout directions", completed: true },
      { id: "st_2", title: "Build responsive hero prototype in Figma", completed: true },
      { id: "st_3", title: "Handoff tokens to frontend team", completed: false },
    ],
    comments: [
      {
        id: "cm_1",
        user: USERS[1],
        message: "Make sure the dark emerald gradient matches our brand guidelines (#0F2D29)!",
        createdAt: daysOffset(-2),
      },
      {
        id: "cm_2",
        user: ME,
        message: "Added the brand color tokens and tested accessibility contrast ratios.",
        createdAt: daysOffset(-1),
      },
    ],
    attachments: [
      {
        id: "att_1",
        fileName: "hero-explorations-v2.fig",
        fileUrl: "https://figma.com/file/hero-explorations",
        publicId: "figma_hero_v2",
        fileType: "figma",
        fileSize: 4200000,
        uploadedBy: USERS[1],
        uploadedAt: daysOffset(-3),
      },
    ],
    isArchived: false,
    createdBy: USERS[1],
    createdAt: daysOffset(-10),
    updatedAt: daysOffset(-1),
  },
  {
    id: "task_2",
    title: "Set up CI/CD pipeline for AWS EKS deployment",
    description: "Configure GitHub Actions workflows to auto-build Docker containers, execute integration test suites, and deploy to staging EKS cluster.",
    board: BOARDS[2],
    project: PROJECTS[2],
    workspace: WORKSPACES[1],
    sprint: SPRINTS[0],
    column: "In Progress",
    assignee: USERS[2],
    watchers: [ME, USERS[4]],
    status: "in_progress",
    priority: "urgent",
    tags: ["devops", "aws", "docker"],
    dueDate: daysOffset(2),
    estimatedHours: 16,
    actualHours: 11,
    subtasks: [
      { id: "st_4", title: "Docker multi-stage build optimization", completed: true },
      { id: "st_5", title: "Configure IAM OIDC roles for GitHub Actions", completed: true },
      { id: "st_6", title: "Automate Helm chart deployment stage", completed: false },
    ],
    comments: [
      {
        id: "cm_3",
        user: USERS[2],
        message: "Staging deployment pipeline verified. Testing automated rollback triggers next.",
        createdAt: daysOffset(-1),
      },
    ],
    attachments: [
      {
        id: "att_2",
        fileName: "pipeline-architecture.pdf",
        fileUrl: "https://storage.nimbus.io/docs/pipeline-arch.pdf",
        publicId: "pdf_pipeline_arch",
        fileType: "pdf",
        fileSize: 1850000,
        uploadedBy: USERS[2],
        uploadedAt: daysOffset(-4),
      },
    ],
    isArchived: false,
    createdBy: USERS[2],
    createdAt: daysOffset(-12),
    updatedAt: daysOffset(-1),
  },
  {
    id: "task_3",
    title: "Integrate Stripe webhook retries & idempotency keys",
    description: "Handle async payment confirmation events safely. Add database level idempotency locks and exponential backoff retry policies.",
    board: BOARDS[0],
    project: PROJECTS[3],
    workspace: WORKSPACES[2],
    sprint: SPRINTS[0],
    column: "In Review",
    assignee: USERS[3],
    watchers: [USERS[1], USERS[2]],
    status: "blocked",
    priority: "urgent",
    tags: ["stripe", "billing", "backend"],
    dueDate: daysOffset(-1),
    estimatedHours: 8,
    actualHours: 9,
    subtasks: [
      { id: "st_7", title: "Construct Stripe signature verification middleware", completed: true },
      { id: "st_8", title: "Redis lock key implementation for webhooks", completed: true },
    ],
    comments: [
      {
        id: "cm_4",
        user: USERS[3],
        message: "Currently blocked waiting for payments sandbox API credentials update from security team.",
        createdAt: daysOffset(-1),
      },
    ],
    attachments: [],
    isArchived: false,
    createdBy: USERS[3],
    createdAt: daysOffset(-8),
    updatedAt: daysOffset(-1),
  },
  {
    id: "task_4",
    title: "Refactor Button & Modal UI Component System",
    description: "Standardize prop interfaces, aria attributes, keyboard navigation focus traps, and theme variant tokens across design system.",
    board: BOARDS[0],
    project: PROJECTS[0],
    workspace: WORKSPACES[0],
    sprint: SPRINTS[0],
    column: "In Review",
    assignee: ME,
    watchers: [USERS[4]],
    status: "in_review",
    priority: "medium",
    tags: ["design-system", "frontend", "a11y"],
    dueDate: daysOffset(4),
    estimatedHours: 6,
    actualHours: 4.5,
    subtasks: [
      { id: "st_9", title: "Refactor Button variants & size tokens", completed: true },
      { id: "st_10", title: "Modal focus trap and ESC dismiss listener", completed: true },
      { id: "st_11", title: "Add Storybook component stories", completed: true },
    ],
    comments: [
      {
        id: "cm_5",
        user: USERS[4],
        message: "Reviewed PR #142 — components look super smooth and accessible!",
        createdAt: daysOffset(-1),
      },
    ],
    attachments: [],
    isArchived: false,
    createdBy: USERS[1],
    createdAt: daysOffset(-6),
    updatedAt: daysOffset(-1),
  },
  {
    id: "task_5",
    title: "Audit WCAG 2.1 AA accessibility compliance",
    description: "Run automated axe-core scans and manual keyboard + screen reader tests across core user dashboard flows.",
    board: BOARDS[0],
    project: PROJECTS[0],
    workspace: WORKSPACES[0],
    sprint: SPRINTS[1],
    column: "To Do",
    assignee: USERS[4],
    watchers: [USERS[1]],
    status: "todo",
    priority: "high",
    tags: ["a11y", "qa", "audit"],
    dueDate: daysOffset(7),
    estimatedHours: 10,
    actualHours: 2,
    subtasks: [
      { id: "st_12", title: "Run axe-core scan on dashboard routes", completed: false },
      { id: "st_13", title: "VoiceOver screen reader navigation test", completed: false },
    ],
    comments: [],
    attachments: [],
    isArchived: false,
    createdBy: USERS[4],
    createdAt: daysOffset(-4),
    updatedAt: daysOffset(-4),
  },
  {
    id: "task_6",
    title: "Optimize LCP and image loading performance",
    description: "Implement WebP/AVIF next-gen formats, responsive srcset, below-the-fold lazy loading, and critical CSS inline optimization.",
    board: BOARDS[1],
    project: PROJECTS[1],
    workspace: WORKSPACES[0],
    sprint: SPRINTS[0],
    column: "Testing",
    assignee: USERS[2],
    watchers: [ME],
    status: "testing",
    priority: "high",
    tags: ["performance", "mobile", "vite"],
    dueDate: daysOffset(5),
    estimatedHours: 8,
    actualHours: 7.5,
    subtasks: [
      { id: "st_14", title: "Convert static assets to WebP", completed: true },
      { id: "st_15", title: "Preload LCP hero banner font & images", completed: true },
      { id: "st_16", title: "Audit Lighthouse score > 95", completed: false },
    ],
    comments: [],
    attachments: [],
    isArchived: false,
    createdBy: USERS[2],
    createdAt: daysOffset(-9),
    updatedAt: daysOffset(-2),
  },
  {
    id: "task_7",
    title: "Migrate blog engine & CMS content to Headless GraphQL",
    description: "Migrate legacy Markdown files to headless CMS and construct automated GraphQL schema generation.",
    board: BOARDS[0],
    project: PROJECTS[0],
    workspace: WORKSPACES[0],
    sprint: SPRINTS[0],
    column: "Completed",
    assignee: USERS[3],
    watchers: [USERS[5]],
    status: "completed",
    completedAt: daysOffset(-2),
    priority: "medium",
    tags: ["cms", "graphql", "content"],
    dueDate: daysOffset(-2),
    estimatedHours: 14,
    actualHours: 13,
    subtasks: [
      { id: "st_17", title: "Export legacy markdown database", completed: true },
      { id: "st_18", title: "Setup GraphQL endpoint & query caching", completed: true },
    ],
    comments: [
      {
        id: "cm_6",
        user: USERS[5],
        message: "All 140+ blog posts migrated cleanly with 301 redirect map in place!",
        createdAt: daysOffset(-2),
      },
    ],
    attachments: [],
    isArchived: false,
    createdBy: USERS[3],
    createdAt: daysOffset(-15),
    updatedAt: daysOffset(-2),
  },
  {
    id: "task_8",
    title: "Build multi-tenant workspace security policy engine",
    description: "Implement role-based access control (RBAC) middleware verifying workspace owner, admin, and member permissions.",
    board: BOARDS[2],
    project: PROJECTS[2],
    workspace: WORKSPACES[1],
    sprint: SPRINTS[1],
    column: "Backlog",
    assignee: USERS[2],
    watchers: [USERS[3]],
    status: "todo",
    priority: "urgent",
    tags: ["security", "rbac", "auth"],
    dueDate: daysOffset(14),
    estimatedHours: 20,
    actualHours: 0,
    subtasks: [
      { id: "st_19", title: "Draft RBAC permission matrix doc", completed: false },
      { id: "st_20", title: "JWT payload workspace permission claims", completed: false },
    ],
    comments: [],
    attachments: [],
    isArchived: false,
    createdBy: USERS[2],
    createdAt: daysOffset(-3),
    updatedAt: daysOffset(-3),
  },
];
